name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  regress:
    name: regress
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['14', '15', '17', '18']

    steps:

      - name: Check out code
        uses: actions/checkout@v7

      - name: Run tests
        run: |
          docker build . --file docker/regress/Dockerfile --build-arg=PG_VERSION=${{ matrix.version }} --tag ttt-regress:${{ matrix.version }}
          docker run ttt-regress:${{ matrix.version }}

  regress-cassert:
    name: regress-cassert
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['14', '15', '17', '18']

    steps:

      - name: Check out code
        uses: actions/checkout@v7

      - name: Run tests
        run: |
          docker build . --file docker/regress/Dockerfile.cpg --build-arg=PG_MAJOR=${{ matrix.version }} --tag ttt-regress-cassert:${{ matrix.version }}
          docker run ttt-regress-cassert:${{ matrix.version }}
